model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2 #12
    num_workers: 1  #  For batch of 4: 0 is best, 2 is good, 1 is worse, 4 is terrible
    wrap: True
    train:
      target: taming.data.faceshq.CelebAHQTrain
      params:
        size: 256
        #degradation: pil_nearest
    validation:
      target: taming.data.faceshq.CelebAHQValidation
      params:
        size: 256
        #degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 4000
        max_images: 8
        increase_log_steps: True
        log_first_step: True

  trainer:
    benchmark: True
    #accumulate_grad_batches: 2    ##LOOK HERE FOR PERFORMANCE PROBLEMS
