model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: segmentation
    image_size: 64
    channels: 3
    # concat_mode: true
    conditioning_key: crossattn
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 128
        use_checkpoint: true
        legacy: False
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt 
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.SpatialRescalerNaiveEmbedding
      params:
        n_stages: 2
        in_channels: 3 #182 one-hot
        out_channels: 128
        ch: 128 # gotta match the unet

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2 #48
    num_workers: 2
    wrap: True
    train:
      target: ldm.data.coco.CocoImagesAndCaptionsTrain
      params:
        size: 256
        # augment: True
    validation:
      target: ldm.data.coco.CocoImagesAndCaptionsValidation
      params:
        size: 256
        # augment: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000
        max_images: 8
        increase_log_steps: False
        log_first_step: True

  trainer:
    benchmark: True